version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/annulleringer"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/forstegangsbehandling"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "gradle"
    directory: "/annulleringer"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "gradle"
    directory: "/forstegangsbehandling"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
